version: '4.29.0'
services:
  db:  
    image: postgres:latest
    environment:
      - POSTGRES_DB=NBA
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
    ports:
      - "5432:5432"

